# -*- coding: utf-8 -*-
"""Erzeugt die theme.css eines Decks aus einer style.toml.

    python -m tools.theme <style.toml> <theme.css>
    python tools/theme.py style.toml slides/web/theme.css

Die style.toml ist dieselbe wie bei slidekit ([colors], [fonts], [sizes]),
so dass ein Projekt eine Designaussage fuer beide Werkzeuge hat. Punktgroessen
werden auf die 1920x1080-Leinwand umgerechnet (1 pt = 2 px). Optional:

    [stagekit]
    lowercase = true        # Folientext kleingeschrieben (Standard)
    margin = 120            # Rand in px
    parts = { "switches" = "009EE3", ... }   # Farbe je Teil fuer die Ortsangabe

[colors.light] mit denselben Schluesseln liefert die Palette fuer hellen Grund;
sie wird als :root[data-theme="light"] in die theme.css geschrieben.
"""
import pathlib
import sys
import tomllib

KEYS = [("background", "bg"), ("white", "white"), ("gray_light", "gray-light"), ("gray", "gray"),
        ("gray_dark", "gray-dark"), ("blue", "blue"), ("green", "green"), ("yellow", "yellow"), ("red", "red")]
DEFAULTS = {"background": "000000", "white": "FFFFFF", "gray_light": "B6BEC6", "gray": "7D868F",
            "gray_dark": "4A5259", "blue": "009EE3", "green": "4ADE80", "yellow": "FFD23F", "red": "FF4D6D"}


def render(style):
    colors = {**DEFAULTS, **style.get("colors", {})}
    fonts = {"text": "Arial", "code": "Roboto Mono", **style.get("fonts", {})}
    sizes = {"large": 40, "normal": 24, "small": 16, "tiny": 10, **style.get("sizes", {})}
    sk = style.get("stagekit", {})
    lines = ["/* generated by stagekit/tools/theme.py from style.toml; edit the toml, not this file */", ":root {"]
    for key, var in KEYS:
        lines.append(f"  --{var}: #{colors[key].lower()};")
    lines.append(f'  --font: "{fonts["text"]}", "Helvetica Neue", Arial, sans-serif;')
    lines.append(f'  --mono: "{fonts["code"]}", Consolas, monospace;')
    for k in ("large", "normal", "small", "tiny"):
        lines.append(f"  --{k}: {int(sizes[k]) * 2}px;")
    lines.append("  --slide-w: 1920px;\n  --slide-h: 1080px;")
    lines.append(f"  --margin: {int(sk.get('margin', 120))}px;")
    lines.append("  --part-color: var(--blue);")
    lines.append(f"  --lowercase: {'lowercase' if sk.get('lowercase', True) else 'none'};")
    lines.append("}")
    light = colors.get("light")
    if isinstance(light, dict):
        # same roles, other values: a deck or a figure rendered with ?theme=light
        # (draw.js sets data-theme from the query) picks these up automatically
        lines.append(':root[data-theme="light"] {')
        for key, var in KEYS:
            lines.append(f"  --{var}: #{light.get(key, colors[key]).lower()};")
        lines.append("}")
    if fonts["code"].lower().startswith("roboto mono"):
        lines.insert(1, '@import url("https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;500&display=swap");')
    return "\n".join(lines) + "\n"


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    src, dst = pathlib.Path(argv[0]), pathlib.Path(argv[1])
    style = tomllib.loads(src.read_text(encoding="utf-8"))
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(render(style), encoding="utf-8")
    print(f"theme: {dst}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
